import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pradeep Sahu Portfolio",
  description: "Generated by create next app",
  openGraph: {
    title: "Pradeep Sahu Portfolio",
    description: "A full-stack developer's portfolio",
    url: "https://pradeepsahu.com",
    images: [
      {
        url: "https://avatars.githubusercontent.com/u/94203408?v=4",
        width: 800,
        height: 600,
        alt: "Pradeep Sahu Portfolio",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Pradeep Sahu Portfolio",
    description: "A full-stack developer's portfolio",
    images: ["https://x.com/Pradeepsahu__/photo"],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
  },
  custom: {
    author: "Pradeep Sahu",
    keywords: ["Pradeep Sahu", "Portfolio", "Full-Stack Developer"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
