import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pradeep Sahu Portfolio",
  description: "Generated by create next app",
  openGraph: {
    title: "Pradeep Sahu Portfolio",
    description: "A full-stack developer's portfolio",
    url: "https://pradeepsahu.com",
    images: [
      {
        url: "https://pradeepsahu.com/og-image.jpg",
        width: 800,
        height: 600,
        alt: "Pradeep Sahu Portfolio",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Pradeep Sahu Portfolio",
    description: "A full-stack developer's portfolio",
    images: ["https://pradeepsahu.com/twitter-image.jpg"],
  },
  viewport: "width=device-width, initial-scale=1",
  robots: {
    index: true,
    follow: true,
    nocache: false,
  },
  themeColor: "#ffffff",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/shortcut-icon.png",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  custom: {
    author: "Pradeep Sahu",
    keywords: ["Pradeep Sahu", "Portfolio", "Full-Stack Developer"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
